on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - 'main'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '30 5 * * *'
jobs:
  integrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - name: Check linting and formatting
        run: npm run lint
      - name: SonarQube scan
        run: npx sonarqube-scanner -Dsonar.projectName=${{ github.repository}} -Dsonar.login=${{ vars.TSG_INNOLAB_SONARQUBE_USER }} -Dsonar.password=${{ secrets.TSG_INNOLAB_SONARQUBE_PASSWORD }} -Dsonar.host.url=${{ vars.TSG_INNOLAB_SONARQUBE_URL }}

      - name: Vulnerability scan
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b .
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b .
          ./syft . -o cyclonedx-xml > sbom.xml
          ./grype sbom.xml --fail-on critical